version: '3'

vars:
  pattern: 'avif'
  include: '*.zip'
  base: '.'
  tmp: 'scripts/ugrep_tmp.bin'

tasks:
  ugrep-fullpath-unix:
    desc: "在类 Unix 环境下运行 ugrep 并把结果转为绝对路径（使用 realpath）"
    cmds:
      - "ugrep -0 -L -r -i --include='{{.include}}' '{{.pattern}}' {{.base}} | xargs -0 realpath"
    silent: false

  # Windows: 先把 NUL 分隔输出写入临时文件，然后用 pwsh 读取并 Resolve-Path
  ugrep-null-to-file-windows:
    desc: "在 Windows 下将 ugrep 的 NUL 输出写入临时文件"
    cmds:
      - "ugrep -0 -L -r -i --include=\"{{.include}}\" \"{{.pattern}}\" {{.base}} > {{.tmp}}"
    silent: false

  ugrep-fullpath-windows:
    desc: "读取临时文件并把 NUL 分隔的路径解析为绝对路径（PowerShell）"
    deps:
      - ugrep-null-to-file-windows
    cmds:
      - |
        pwsh -NoProfile -Command &{
          $s = Get-Content -Raw -Encoding UTF8 '{{.tmp}}';
          if (-not $s) { Write-Output '<no output>'; exit }
          $parts = $s -split "`0";
          foreach ($p in $parts) {
            if ($p -ne '') {
              try {
                Resolve-Path -LiteralPath $p -ErrorAction Stop | ForEach-Object { $_.Path }
              } catch {
                Write-Warning "无法解析路径: $p"
              }
            }
          }
        }
    silent: false

  # 方便的提示任务（不执行，只说明如何运行）
  ugrep-fullpath-help:
    desc: "显示如何在当前平台运行相应任务"
    cmds:
      - "echo 'Run `task ugrep-fullpath-unix` on Unix-like systems or `task ugrep-fullpath-windows` on Windows (pwsh) when ugrep is installed.'"
    silent: false
